<body vlink="#FFFFFF" link="#FFFFFF" style="zoom: 1;">

<script language="JavaScript">
var currentpos,timer; 
function initialize() 
{ 
timer=setInterval("scrollwindow()",10);
} 
function sc(){
clearInterval(timer); 
}
function scrollwindow() 
{ 
currentpos=document.body.scrollTop; 
window.scroll(0,++currentpos); 
if (currentpos != document.body.scrollTop) 
sc();
} 
document.onmousedown=sc
document.ondblclick=initialize
</script>
<div style="position:absolute;top:0;left:0"><img width="850" height="1100" src="pg_0001.jpg"></div>
<div style="position:absolute;top:132;left:441"><nobr><span class="ft0">U</span></nobr></div>
<div style="position:absolute;top:132;left:460"><nobr><span class="ft0">.</span></nobr></div>
<div style="position:absolute;top:132;left:466"><nobr><span class="ft0">S</span></nobr></div>
<div style="position:absolute;top:132;left:481"><nobr><span class="ft0">.</span></nobr></div>
<div style="position:absolute;top:132;left:487"><nobr><span class="ft0">&nbsp;</span></nobr></div>
<div style="position:absolute;top:132;left:494"><nobr><span class="ft0">Market</span></nobr></div>
<div style="position:absolute;top:132;left:577"><nobr><span class="ft0">&nbsp;</span></nobr></div>
<div style="position:absolute;top:132;left:583"><nobr><span class="ft0">S</span></nobr></div>
<div style="position:absolute;top:132;left:598"><nobr><span class="ft0">h</span></nobr></div>
<div style="position:absolute;top:132;left:612"><nobr><span class="ft0">a</span></nobr></div>
<div style="position:absolute;top:132;left:625"><nobr><span class="ft0">r</span></nobr></div>
<div style="position:absolute;top:132;left:636"><nobr><span class="ft0">e</span></nobr></div>
<div style="position:absolute;top:132;left:648"><nobr><span class="ft0">&nbsp;</span></nobr></div>
<div style="position:absolute;top:246;left:141"><nobr><span class="ft1">Market Statistics</span></nobr></div>
<div style="position:absolute;top:271;left:169"><nobr><span class="ft2">U</span></nobr></div>
<div style="position:absolute;top:271;left:181"><nobr><span class="ft2">S</span></nobr></div>
<div style="position:absolute;top:271;left:189"><nobr><span class="ft2">&nbsp;T</span></nobr></div>
<div style="position:absolute;top:271;left:203"><nobr><span class="ft2">o</span></nobr></div>
<div style="position:absolute;top:271;left:211"><nobr><span class="ft2">ta</span></nobr></div>
<div style="position:absolute;top:271;left:224"><nobr><span class="ft2">l&nbsp;U</span></nobr></div>
<div style="position:absolute;top:271;left:243"><nobr><span class="ft2">n</span></nobr></div>
<div style="position:absolute;top:271;left:252"><nobr><span class="ft2">its</span></nobr></div>
<div style="position:absolute;top:271;left:298"><nobr><span class="ft2">1</span></nobr></div>
<div style="position:absolute;top:271;left:306"><nobr><span class="ft2">1</span></nobr></div>
<div style="position:absolute;top:271;left:313"><nobr><span class="ft2">5</span></nobr></div>
<div style="position:absolute;top:271;left:321"><nobr><span class="ft2">.2</span></nobr></div>
<div style="position:absolute;top:291;left:158"><nobr><span class="ft2">W</span></nobr></div>
<div style="position:absolute;top:291;left:174"><nobr><span class="ft2">W</span></nobr></div>
<div style="position:absolute;top:291;left:189"><nobr><span class="ft2">&nbsp;T</span></nobr></div>
<div style="position:absolute;top:291;left:203"><nobr><span class="ft2">o</span></nobr></div>
<div style="position:absolute;top:291;left:211"><nobr><span class="ft2">ta</span></nobr></div>
<div style="position:absolute;top:291;left:224"><nobr><span class="ft2">l&nbsp;U</span></nobr></div>
<div style="position:absolute;top:291;left:243"><nobr><span class="ft2">n</span></nobr></div>
<div style="position:absolute;top:291;left:252"><nobr><span class="ft2">it</span></nobr></div>
<div style="position:absolute;top:291;left:262"><nobr><span class="ft2">s</span></nobr></div>
<div style="position:absolute;top:291;left:298"><nobr><span class="ft2">3</span></nobr></div>
<div style="position:absolute;top:291;left:306"><nobr><span class="ft2">7</span></nobr></div>
<div style="position:absolute;top:291;left:313"><nobr><span class="ft2">6</span></nobr></div>
<div style="position:absolute;top:291;left:321"><nobr><span class="ft2">.1</span></nobr></div>
<div style="position:absolute;top:310;left:192"><nobr><span class="ft2">U</span></nobr></div>
<div style="position:absolute;top:310;left:203"><nobr><span class="ft2">S</span></nobr></div>
<div style="position:absolute;top:310;left:212"><nobr><span class="ft2">&nbsp;G</span></nobr></div>
<div style="position:absolute;top:310;left:228"><nobr><span class="ft2">r</span></nobr></div>
<div style="position:absolute;top:310;left:235"><nobr><span class="ft2">o</span></nobr></div>
<div style="position:absolute;top:310;left:243"><nobr><span class="ft2">w</span></nobr></div>
<div style="position:absolute;top:310;left:254"><nobr><span class="ft2">th</span></nobr></div>
<div style="position:absolute;top:310;left:302"><nobr><span class="ft2">1</span></nobr></div>
<div style="position:absolute;top:310;left:310"><nobr><span class="ft2">2</span></nobr></div>
<div style="position:absolute;top:310;left:318"><nobr><span class="ft2">%</span></nobr></div>
<div style="position:absolute;top:330;left:181"><nobr><span class="ft2">W</span></nobr></div>
<div style="position:absolute;top:330;left:197"><nobr><span class="ft2">W</span></nobr></div>
<div style="position:absolute;top:330;left:212"><nobr><span class="ft2">&nbsp;G</span></nobr></div>
<div style="position:absolute;top:330;left:228"><nobr><span class="ft2">r</span></nobr></div>
<div style="position:absolute;top:330;left:235"><nobr><span class="ft2">o</span></nobr></div>
<div style="position:absolute;top:330;left:243"><nobr><span class="ft2">w</span></nobr></div>
<div style="position:absolute;top:330;left:254"><nobr><span class="ft2">th</span></nobr></div>
<div style="position:absolute;top:330;left:305"><nobr><span class="ft2">-3</span></nobr></div>
<div style="position:absolute;top:330;left:318"><nobr><span class="ft2">%</span></nobr></div>
<div style="position:absolute;top:370;left:141"><nobr><span class="ft1">Market Share</span></nobr></div>
<div style="position:absolute;top:370;left:301"><nobr><span class="ft1">U</span></nobr></div>
<div style="position:absolute;top:370;left:314"><nobr><span class="ft1">S</span></nobr></div>
<div style="position:absolute;top:370;left:324"><nobr><span class="ft1">&nbsp;&nbsp;</span></nobr></div>
<div style="position:absolute;top:395;left:141"><nobr><span class="ft3">&nbsp;*</span></nobr></div>
<div style="position:absolute;top:395;left:152"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:395;left:160"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:395;left:168"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:395;left:176"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:395;left:183"><nobr><span class="ft3">&nbsp;S</span></nobr></div>
<div style="position:absolute;top:395;left:196"><nobr><span class="ft3">y</span></nobr></div>
<div style="position:absolute;top:395;left:204"><nobr><span class="ft3">s</span></nobr></div>
<div style="position:absolute;top:395;left:210"><nobr><span class="ft3">te</span></nobr></div>
<div style="position:absolute;top:395;left:221"><nobr><span class="ft3">m</span></nobr></div>
<div style="position:absolute;top:395;left:233"><nobr><span class="ft3">s</span></nobr></div>
<div style="position:absolute;top:409;left:239"><nobr><span class="ft4">&nbsp;</span></nobr></div>
<div style="position:absolute;top:395;left:291"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:395;left:299"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:395;left:307"><nobr><span class="ft3">.4</span></nobr></div>
<div style="position:absolute;top:395;left:318"><nobr><span class="ft3">%</span></nobr></div>
<div style="position:absolute;top:414;left:141"><nobr><span class="ft3">&nbsp;*</span></nobr></div>
<div style="position:absolute;top:414;left:152"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:160"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:168"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:176"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:183"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:191"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:199"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:207"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:214"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:222"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:414;left:230"><nobr><span class="ft3">&nbsp;</span></nobr></div>
<div style="position:absolute;top:428;left:234"><nobr><span class="ft4">&nbsp;</span></nobr></div>
<div style="position:absolute;top:414;left:291"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:414;left:299"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:414;left:307"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:414;left:318"><nobr><span class="ft3">%</span></nobr></div>
<div style="position:absolute;top:434;left:141"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:148"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:156"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:164"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:172"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:179"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:187"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:195"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:203"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:210"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:218"><nobr><span class="ft3">*</span></nobr></div>
<div style="position:absolute;top:434;left:226"><nobr><span class="ft3">&nbsp;</span></nobr></div>
<div style="position:absolute;top:448;left:230"><nobr><span class="ft4">&nbsp;</span></nobr></div>
<div style="position:absolute;top:434;left:292"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:434;left:299"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:434;left:307"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:434;left:319"><nobr><span class="ft3">%</span></nobr></div>
<div style="position:absolute;top:453;left:141"><nobr><span class="ft3">&nbsp;A</span></nobr></div>
<div style="position:absolute;top:453;left:156"><nobr><span class="ft3">ll&nbsp;O</span></nobr></div>
<div style="position:absolute;top:453;left:179"><nobr><span class="ft3">th</span></nobr></div>
<div style="position:absolute;top:453;left:191"><nobr><span class="ft3">e</span></nobr></div>
<div style="position:absolute;top:453;left:198"><nobr><span class="ft3">r</span></nobr></div>
<div style="position:absolute;top:467;left:204"><nobr><span class="ft4">&nbsp;</span></nobr></div>
<div style="position:absolute;top:453;left:293"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:453;left:301"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:453;left:308"><nobr><span class="ft3">.5</span></nobr></div>
<div style="position:absolute;top:453;left:320"><nobr><span class="ft3">%</span></nobr></div>
<div style="position:absolute;top:559;left:300"><nobr><span class="ft5">S</span></nobr></div>
<div style="position:absolute;top:559;left:316"><nobr><span class="ft5">t</span></nobr></div>
<div style="position:absolute;top:559;left:323"><nobr><span class="ft5">e</span></nobr></div>
<div style="position:absolute;top:559;left:336"><nobr><span class="ft5">l</span></nobr></div>
<div style="position:absolute;top:559;left:343"><nobr><span class="ft5">l</span></nobr></div>
<div style="position:absolute;top:559;left:349"><nobr><span class="ft5">a</span></nobr></div>
<div style="position:absolute;top:559;left:362"><nobr><span class="ft5">r</span></nobr></div>
<div style="position:absolute;top:559;left:425"><nobr><span class="ft5">P</span></nobr></div>
<div style="position:absolute;top:559;left:440"><nobr><span class="ft5">h</span></nobr></div>
<div style="position:absolute;top:559;left:455"><nobr><span class="ft5">o</span></nobr></div>
<div style="position:absolute;top:559;left:469"><nobr><span class="ft5">t</span></nobr></div>
<div style="position:absolute;top:559;left:477"><nobr><span class="ft5">o</span></nobr></div>
<div style="position:absolute;top:559;left:491"><nobr><span class="ft5">n</span></nobr></div>
<div style="position:absolute;top:559;left:567"><nobr><span class="ft5">O</span></nobr></div>
<div style="position:absolute;top:559;left:585"><nobr><span class="ft5">r</span></nobr></div>
<div style="position:absolute;top:559;left:594"><nobr><span class="ft5">b</span></nobr></div>
<div style="position:absolute;top:559;left:608"><nobr><span class="ft5">i</span></nobr></div>
<div style="position:absolute;top:559;left:615"><nobr><span class="ft5">t</span></nobr></div>
<div style="position:absolute;top:592;left:179"><nobr><span class="ft6">V</span></nobr></div>
<div style="position:absolute;top:592;left:190"><nobr><span class="ft6">o</span></nobr></div>
<div style="position:absolute;top:592;left:198"><nobr><span class="ft6">lu</span></nobr></div>
<div style="position:absolute;top:592;left:211"><nobr><span class="ft6">m</span></nobr></div>
<div style="position:absolute;top:592;left:224"><nobr><span class="ft6">e</span></nobr></div>
<div style="position:absolute;top:592;left:283"><nobr><span class="ft6">G</span></nobr></div>
<div style="position:absolute;top:592;left:295"><nobr><span class="ft6">r</span></nobr></div>
<div style="position:absolute;top:592;left:302"><nobr><span class="ft6">o</span></nobr></div>
<div style="position:absolute;top:592;left:309"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:315"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:321"><nobr><span class="ft6">&nbsp;$</span></nobr></div>
<div style="position:absolute;top:592;left:356"><nobr><span class="ft6">U</span></nobr></div>
<div style="position:absolute;top:592;left:367"><nobr><span class="ft6">n</span></nobr></div>
<div style="position:absolute;top:592;left:376"><nobr><span class="ft6">it&nbsp;$</span></nobr></div>
<div style="position:absolute;top:592;left:412"><nobr><span class="ft6">G</span></nobr></div>
<div style="position:absolute;top:592;left:424"><nobr><span class="ft6">r</span></nobr></div>
<div style="position:absolute;top:592;left:431"><nobr><span class="ft6">o</span></nobr></div>
<div style="position:absolute;top:592;left:439"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:445"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:451"><nobr><span class="ft6">&nbsp;$</span></nobr></div>
<div style="position:absolute;top:592;left:486"><nobr><span class="ft6">U</span></nobr></div>
<div style="position:absolute;top:592;left:497"><nobr><span class="ft6">n</span></nobr></div>
<div style="position:absolute;top:592;left:505"><nobr><span class="ft6">it&nbsp;$</span></nobr></div>
<div style="position:absolute;top:592;left:542"><nobr><span class="ft6">G</span></nobr></div>
<div style="position:absolute;top:592;left:554"><nobr><span class="ft6">r</span></nobr></div>
<div style="position:absolute;top:592;left:561"><nobr><span class="ft6">o</span></nobr></div>
<div style="position:absolute;top:592;left:568"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:574"><nobr><span class="ft6">s</span></nobr></div>
<div style="position:absolute;top:592;left:580"><nobr><span class="ft6">&nbsp;$</span></nobr></div>
<div style="position:absolute;top:592;left:615"><nobr><span class="ft6">U</span></nobr></div>
<div style="position:absolute;top:592;left:626"><nobr><span class="ft6">n</span></nobr></div>
<div style="position:absolute;top:592;left:635"><nobr><span class="ft6">it&nbsp;$</span></nobr></div>
<div style="position:absolute;top:613;left:193"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:613;left:201"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:209"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:309"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:613;left:317"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:370"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:613;left:378"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:613;left:389"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:431"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:439"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:613;left:447"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:454"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:613;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:499"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:613;left:507"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:613;left:519"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:613;left:561"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:568"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:613;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:613;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:613;left:629"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:613;left:636"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:613;left:648"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:193"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:633;left:201"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:209"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:309"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:633;left:317"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:370"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:633;left:378"><nobr><span class="ft3">.5</span></nobr></div>
<div style="position:absolute;top:633;left:389"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:431"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:439"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:633;left:447"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:633;left:454"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:633;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:499"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:633;left:507"><nobr><span class="ft3">.5</span></nobr></div>
<div style="position:absolute;top:633;left:519"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:633;left:561"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:568"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:633;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:633;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:633;left:629"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:633;left:636"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:633;left:648"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:193"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:652;left:201"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:209"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:309"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:652;left:317"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:652;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:370"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:652;left:378"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:652;left:389"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:652;left:431"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:439"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:652;left:447"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:454"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:652;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:499"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:652;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:652;left:519"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:652;left:561"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:568"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:652;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:652;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:652;left:629"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:652;left:636"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:652;left:648"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:672;left:193"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:672;left:201"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:672;left:209"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:672;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:309"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:672;left:317"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:672;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:672;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:370"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:672;left:378"><nobr><span class="ft3">.8</span></nobr></div>
<div style="position:absolute;top:672;left:389"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:672;left:431"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:439"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:672;left:447"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:672;left:454"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:672;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:499"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:672;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:672;left:519"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:672;left:561"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:568"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:672;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:672;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:672;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:672;left:629"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:672;left:636"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:672;left:648"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:692;left:193"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:692;left:201"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:209"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:309"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:692;left:317"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:370"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:692;left:378"><nobr><span class="ft3">.6</span></nobr></div>
<div style="position:absolute;top:692;left:389"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:427"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:692;left:435"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:692;left:447"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:692;left:454"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:692;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:499"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:692;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:692;left:519"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:692;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:692;left:564"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:692;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:692;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:692;left:629"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:692;left:636"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:692;left:648"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:187"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:711;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:711;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:302"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:309"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:711;left:317"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:711;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:378"><nobr><span class="ft3">.9</span></nobr></div>
<div style="position:absolute;top:711;left:389"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:711;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:427"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:711;left:435"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:711;left:447"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:711;left:454"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:711;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:499"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:711;left:507"><nobr><span class="ft3">.4</span></nobr></div>
<div style="position:absolute;top:711;left:519"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:711;left:564"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:711;left:576"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:711;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:711;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:711;left:629"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:711;left:636"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:711;left:648"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:731;left:187"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:195"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:731;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:731;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:731;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:298"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:306"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:731;left:317"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:731;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:731;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:731;left:378"><nobr><span class="ft3">.7</span></nobr></div>
<div style="position:absolute;top:731;left:389"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:731;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:427"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:435"><nobr><span class="ft3">,6</span></nobr></div>
<div style="position:absolute;top:731;left:447"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:731;left:454"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:731;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:499"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:507"><nobr><span class="ft3">.0</span></nobr></div>
<div style="position:absolute;top:731;left:519"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:731;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:564"><nobr><span class="ft3">,2</span></nobr></div>
<div style="position:absolute;top:731;left:576"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:731;left:584"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:731;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:731;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:731;left:636"><nobr><span class="ft3">.8</span></nobr></div>
<div style="position:absolute;top:731;left:648"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:751;left:187"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:751;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:751;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:298"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:751;left:306"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:751;left:317"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:751;left:325"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:751;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:378"><nobr><span class="ft3">.7</span></nobr></div>
<div style="position:absolute;top:751;left:389"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:751;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:427"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:751;left:435"><nobr><span class="ft3">,8</span></nobr></div>
<div style="position:absolute;top:751;left:447"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:751;left:454"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:751;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:507"><nobr><span class="ft3">.9</span></nobr></div>
<div style="position:absolute;top:751;left:519"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:751;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:751;left:564"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:751;left:576"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:751;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:751;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:751;left:636"><nobr><span class="ft3">.6</span></nobr></div>
<div style="position:absolute;top:751;left:648"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:770;left:187"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:770;left:195"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:770;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:298"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:770;left:306"><nobr><span class="ft3">,7</span></nobr></div>
<div style="position:absolute;top:770;left:317"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:770;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:378"><nobr><span class="ft3">.7</span></nobr></div>
<div style="position:absolute;top:770;left:389"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:770;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:770;left:435"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:770;left:447"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:770;left:454"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:770;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:507"><nobr><span class="ft3">.8</span></nobr></div>
<div style="position:absolute;top:770;left:519"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:770;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:770;left:564"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:770;left:576"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:770;left:584"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:770;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:770;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:770;left:636"><nobr><span class="ft3">.6</span></nobr></div>
<div style="position:absolute;top:770;left:648"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:790;left:187"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:790;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:790;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:298"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:790;left:306"><nobr><span class="ft3">,8</span></nobr></div>
<div style="position:absolute;top:790;left:317"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:790;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:378"><nobr><span class="ft3">.6</span></nobr></div>
<div style="position:absolute;top:790;left:389"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:790;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:790;left:435"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:790;left:447"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:790;left:454"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:790;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:507"><nobr><span class="ft3">.7</span></nobr></div>
<div style="position:absolute;top:790;left:519"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:790;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:790;left:564"><nobr><span class="ft3">,7</span></nobr></div>
<div style="position:absolute;top:790;left:576"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:790;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:790;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:790;left:636"><nobr><span class="ft3">.5</span></nobr></div>
<div style="position:absolute;top:790;left:648"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:810;left:187"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:810;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:810;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:298"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:810;left:306"><nobr><span class="ft3">,9</span></nobr></div>
<div style="position:absolute;top:810;left:317"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:810;left:325"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:378"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:810;left:389"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:810;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:810;left:435"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:810;left:447"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:454"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:507"><nobr><span class="ft3">.5</span></nobr></div>
<div style="position:absolute;top:810;left:519"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:810;left:564"><nobr><span class="ft3">,8</span></nobr></div>
<div style="position:absolute;top:810;left:576"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:810;left:584"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:810;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:810;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:810;left:636"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:810;left:648"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:829;left:187"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:829;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:829;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:829;left:306"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:829;left:317"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:325"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:829;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:378"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:829;left:389"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:829;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:829;left:435"><nobr><span class="ft3">,5</span></nobr></div>
<div style="position:absolute;top:829;left:447"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:829;left:454"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:829;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:507"><nobr><span class="ft3">.4</span></nobr></div>
<div style="position:absolute;top:829;left:519"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:829;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:829;left:564"><nobr><span class="ft3">,9</span></nobr></div>
<div style="position:absolute;top:829;left:576"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:829;left:584"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:829;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:829;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:829;left:636"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:829;left:648"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:849;left:187"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:849;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:849;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:849;left:306"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:849;left:317"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:849;left:325"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:849;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:378"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:849;left:389"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:849;left:435"><nobr><span class="ft3">,6</span></nobr></div>
<div style="position:absolute;top:849;left:447"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:849;left:454"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:849;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:849;left:519"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:849;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:557"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:849;left:564"><nobr><span class="ft3">,9</span></nobr></div>
<div style="position:absolute;top:849;left:576"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:849;left:584"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:849;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:849;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:849;left:636"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:849;left:648"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:869;left:187"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:869;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:869;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:869;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:869;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:869;left:306"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:869;left:317"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:869;left:325"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:869;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:869;left:378"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:869;left:389"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:869;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:869;left:435"><nobr><span class="ft3">,7</span></nobr></div>
<div style="position:absolute;top:869;left:447"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:869;left:454"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:869;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:869;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:869;left:519"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:869;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:557"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:869;left:564"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:869;left:576"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:869;left:584"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:869;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:869;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:869;left:636"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:869;left:648"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:888;left:187"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:888;left:195"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:888;left:207"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:214"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:888;left:306"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:888;left:317"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:888;left:325"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:888;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:378"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:888;left:389"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:888;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:888;left:435"><nobr><span class="ft3">,8</span></nobr></div>
<div style="position:absolute;top:888;left:447"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:888;left:454"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:888;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:507"><nobr><span class="ft3">.3</span></nobr></div>
<div style="position:absolute;top:888;left:519"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:888;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:557"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:888;left:564"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:888;left:576"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:888;left:584"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:888;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:888;left:636"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:888;left:648"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:908;left:183"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:908;left:191"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:199"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:908;left:210"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:218"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:908;left:306"><nobr><span class="ft3">,2</span></nobr></div>
<div style="position:absolute;top:908;left:317"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:908;left:325"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:908;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:378"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:908;left:389"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:908;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:908;left:435"><nobr><span class="ft3">,8</span></nobr></div>
<div style="position:absolute;top:908;left:447"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:908;left:454"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:908;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:507"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:908;left:519"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:908;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:557"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:908;left:564"><nobr><span class="ft3">,1</span></nobr></div>
<div style="position:absolute;top:908;left:576"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:908;left:584"><nobr><span class="ft3">4</span></nobr></div>
<div style="position:absolute;top:908;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:908;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:908;left:636"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:908;left:648"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:928;left:183"><nobr><span class="ft3">1</span></nobr></div>
<div style="position:absolute;top:928;left:191"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:928;left:199"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:928;left:210"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:218"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:928;left:306"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:928;left:317"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:928;left:325"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:928;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:378"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:928;left:389"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:928;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:427"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:928;left:435"><nobr><span class="ft3">,9</span></nobr></div>
<div style="position:absolute;top:928;left:447"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:928;left:454"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:928;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:507"><nobr><span class="ft3">.2</span></nobr></div>
<div style="position:absolute;top:928;left:519"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:557"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:928;left:564"><nobr><span class="ft3">,2</span></nobr></div>
<div style="position:absolute;top:928;left:576"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:928;left:584"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:928;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:928;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:928;left:636"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:928;left:648"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:947;left:183"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:947;left:191"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:199"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:947;left:210"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:218"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:290"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:298"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:947;left:306"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:947;left:317"><nobr><span class="ft3">9</span></nobr></div>
<div style="position:absolute;top:947;left:325"><nobr><span class="ft3">8</span></nobr></div>
<div style="position:absolute;top:947;left:362"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:370"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:378"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:947;left:389"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:947;left:420"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:427"><nobr><span class="ft3">3</span></nobr></div>
<div style="position:absolute;top:947;left:435"><nobr><span class="ft3">,0</span></nobr></div>
<div style="position:absolute;top:947;left:447"><nobr><span class="ft3">7</span></nobr></div>
<div style="position:absolute;top:947;left:454"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:947;left:492"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:499"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:507"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:947;left:519"><nobr><span class="ft3">5</span></nobr></div>
<div style="position:absolute;top:947;left:549"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:557"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:947;left:564"><nobr><span class="ft3">,3</span></nobr></div>
<div style="position:absolute;top:947;left:576"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:584"><nobr><span class="ft3">6</span></nobr></div>
<div style="position:absolute;top:947;left:621"><nobr><span class="ft3">$</span></nobr></div>
<div style="position:absolute;top:947;left:629"><nobr><span class="ft3">0</span></nobr></div>
<div style="position:absolute;top:947;left:636"><nobr><span class="ft3">.1</span></nobr></div>
<div style="position:absolute;top:947;left:648"><nobr><span class="ft3">2</span></nobr></div>
<div style="position:absolute;top:246;left:396"><nobr><span class="ft1">U</span></nobr></div>
<div style="position:absolute;top:246;left:409"><nobr><span class="ft1">S</span></nobr></div>
<div style="position:absolute;top:246;left:419"><nobr><span class="ft1">&nbsp;Market Share</span></nobr></div>
<div style="position:absolute;top:482;left:434"><nobr><span class="ft7">&nbsp;*</span></nobr></div>
<div style="position:absolute;top:482;left:443"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:450"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:456"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:463"><nobr><span class="ft7">&nbsp;S</span></nobr></div>
<div style="position:absolute;top:482;left:473"><nobr><span class="ft7">y</span></nobr></div>
<div style="position:absolute;top:482;left:480"><nobr><span class="ft7">ste</span></nobr></div>
<div style="position:absolute;top:482;left:494"><nobr><span class="ft7">m</span></nobr></div>
<div style="position:absolute;top:482;left:504"><nobr><span class="ft7">s</span></nobr></div>
<div style="position:absolute;top:482;left:552"><nobr><span class="ft7">&nbsp;*</span></nobr></div>
<div style="position:absolute;top:482;left:562"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:569"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:575"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:582"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:588"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:595"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:601"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:482;left:608"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:434"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:440"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:447"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:453"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:460"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:466"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:473"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:479"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:486"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:492"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:499"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:505"><nobr><span class="ft7">*</span></nobr></div>
<div style="position:absolute;top:504;left:552"><nobr><span class="ft7">&nbsp;A</span></nobr></div>
<div style="position:absolute;top:504;left:565"><nobr><span class="ft7">ll&nbsp;O</span></nobr></div>
<div style="position:absolute;top:504;left:585"><nobr><span class="ft7">th</span></nobr></div>
<div style="position:absolute;top:504;left:595"><nobr><span class="ft7">e</span></nobr></div>
<div style="position:absolute;top:504;left:601"><nobr><span class="ft7">r</span></nobr></div>
<script language="javascript">
			var currentZoom = parent.ltop.currentZoom;
			if(currentZoom != undefined)
				document.body.style.zoom=currentZoom/100;
			</script>

</body>